// @ts-check
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { flatConfigs as importXFlatConfigs } from "eslint-plugin-import-x";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";
import tseslint from "typescript-eslint";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const domainDir = path.join(__dirname, "packages/domain");

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      ".claude/**",
      "**/*.tsbuildinfo",
      "**/coverage/**",
      "pnpm-lock.yaml",
      // M3-T4c: apps/mobile/.expo/types/router.d.ts is generated by Expo
      // Router's typed-routes feature (app.json experiments.typedRoutes,
      // M3-T1) on every `expo start`/`expo export`. It is machine-written,
      // never hand-edited, and was producing a lint warning before this
      // ignore entry existed.
      "**/.expo/**",
    ],
  },
  js.configs.recommended,
  importXFlatConfigs.recommended,
  {
    // Type-aware linting for real workspace source; root-level tooling
    // config files (this file, vitest.config.ts) are plain TS/JS and are
    // covered by the non-type-checked rules from js.configs.recommended +
    // typescript-eslint's syntax-only parsing below instead — they aren't
    // part of any package's tsconfig "include".
    //
    // "*.tsx" added for apps/mobile (M3-T1): without it these files fell
    // outside every "files" pattern above and were parsed by ESLint's plain
    // espree parser, which cannot read TS syntax (types, `as const`, …) at
    // all, let alone JSX-in-TS.
    files: ["apps/**/*.ts", "apps/**/*.tsx", "packages/**/*.ts"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: { ...globals.node },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
        ecmaFeatures: { jsx: true },
      },
    },
  },
  {
    files: ["*.ts", "*.js"],
    extends: [...tseslint.configs.recommended],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
  // apps/mobile's own CommonJS config files (M3-T1): Expo/Metro/Babel read
  // these directly with Node's CJS loader (not through any package's
  // tsconfig "include", same reasoning as the root-file-only "*.js" block
  // above, which doesn't match these since they're nested under apps/mobile/).
  {
    files: ["apps/mobile/babel.config.js", "apps/mobile/metro.config.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: { ...globals.node, ...globals.commonjs },
    },
  },
  // scripts/**/*.mjs (M1-T5 follow-up, M1-T10-d): outside apps/**/packages/**
  // and not matched by the root-file-only "*.ts"/"*.js" block above, so
  // without this it fell back to ESLint's own default (ecmaVersion 2018,
  // sourceType script, no globals) — forcing scripts/food-data-coverage-
  // research.mjs into ES2018-safe syntax and a manual `/* global */` comment
  // just to lint clean. Plain (non-type-checked) parsing, same as the "*.ts"/
  // "*.js" block: these are standalone Node scripts, not part of any
  // package's tsconfig "include". Extended (M3-T4b review fix) with
  // "packages/*/scripts/**/*.mjs" for the same reason, one level down:
  // packages/adapters/scripts/gen-screening-fixtures.mjs sits outside that
  // package's own tsconfig "include" (its own "rootDir": "src"), so without
  // this addition `import.meta` failed to parse there too.
  {
    files: ["scripts/**/*.mjs", "docs/**/*.mjs", "packages/*/scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.node },
    },
  },
  {
    settings: {
      // TS-aware resolution: understands NodeNext's "./foo.js" -> "./foo.ts"
      // extension mapping and workspace-package resolution, which the plain
      // Node resolver cannot — required for no-restricted-paths below to
      // actually resolve the boundary-check zones. Pinned to the 3.8.x line
      // (see package.json) because it resolves via pure-JS `enhanced-resolve`
      // — 3.9+/4.x switch to a native (Rust/napi) resolver whose postinstall
      // proved unreliable across fresh clones in this environment.
      //
      // `conditionNames` puts the workspace packages' `"source"` export
      // condition ahead of `"types"` (M2-T1 review fix F8). Those packages
      // advertise `dist/` so that the compiled API can import them at runtime,
      // and `dist/` is a build artefact: on a fresh checkout it does not exist
      // yet, and CI runs `pnpm lint` *before* `pnpm typecheck`, which is what
      // builds it. Resolving through `"types"` therefore failed with ten
      // `import-x/no-unresolved` errors on any clean state, and passed only on
      // a machine that happened to have built already. `"source"` points at
      // `src/index.ts`, which is always there, so linting no longer depends on
      // a build having happened first. The rest of the list is the resolver's
      // own default set, restated because supplying `conditionNames` replaces
      // it rather than extending it.
      "import-x/resolver": {
        typescript: {
          alwaysTryTypes: true,
          conditionNames: [
            "source",
            "types",
            "import",
            "require",
            "node",
            "node-addons",
            "browser",
            "default",
          ],
        },
      },
    },
  },
  // --- Dependency-boundary rule (M0-T1) ---
  // packages/domain is the deterministic core (ARCHITECTURE.md §2,
  // CLAUDE.md rule 7): zero runtime dependencies, zero I/O, no imports from
  // adapters or contracts. Scoped to domain's production source only (its
  // *.test.ts files legitimately depend on the shared vitest/fast-check
  // devDependencies, which are not a boundary concern). Enforced three ways:
  //  1. no-extraneous-dependencies — domain/package.json declares zero
  //     dependencies, so ANY bare-specifier import (an npm package, or a
  //     sibling workspace package like @smart-kitchen/adapters) is flagged.
  //     `devDependencies: false` (M1-T10-c) is required for this to bite on
  //     production source: the rule's own default is `devDependencies: true`
  //     (permit them), which let a `fast-check` import into a *production*
  //     domain file lint clean — devDependencies are visible to production
  //     code only in the eyes of this rule, never at runtime, so that default
  //     was silently overclaiming the boundary it exists to guard (M1-T3
  //     review follow-up). With it `false`, only dependencies listed in
  //     domain's zero-entry "dependencies" are permitted here, which is
  //     none.
  //  2. no-restricted-paths — belt-and-suspenders guard against a relative
  //     path reaching into adapters/contracts source directly.
  //  3. no-nodejs-modules — blocks Node built-ins (fs, net, …), which are
  //     not "dependencies" and so wouldn't be caught by rule 1 alone.
  {
    files: ["packages/domain/src/**/*.ts"],
    ignores: ["packages/domain/src/**/*.test.ts"],
    rules: {
      "import-x/no-extraneous-dependencies": [
        "error",
        { packageDir: domainDir, devDependencies: false },
      ],
      "import-x/no-nodejs-modules": "error",
      "import-x/no-restricted-paths": [
        "error",
        {
          zones: [
            {
              target: "./packages/domain/src",
              from: ["./packages/adapters/src", "./packages/contracts/src"],
              message:
                "packages/domain must not depend on adapters or contracts — it is the pure, zero-I/O core (ARCHITECTURE.md §2, CLAUDE.md rule 7).",
            },
          ],
        },
      ],
    },
  },
  // --- apps/mobile domain-boundary rule (M3-T1) ---
  // The mobile client must never import @smart-kitchen/domain directly. Only
  // @smart-kitchen/contracts DTOs cross the client/server seam
  // (ARCHITECTURE.md §2, M3-T1 invariant). @smart-kitchen/adapters is allowed
  // (its fixture data is what the M3-T1 fixture ApiClient reads until an API
  // endpoint exists), just not domain's own package. Proven by
  // apps/mobile/src/lint-rules/domain-boundary.test.ts, which runs this exact
  // rule config against an in-memory source string.
  //
  // Two rules, same reasoning as packages/domain's own block above:
  //  1. no-restricted-imports: catches the bare specifier (@smart-kitchen/
  //     domain) and any deep import into it (@smart-kitchen/domain/*).
  //  2. no-restricted-paths: review finding F1 (M3-T1 review). Rule 1 alone
  //     does not catch a relative path reaching straight into
  //     packages/domain/src (e.g. "../../../packages/domain/src/inventory/
  //     ledger"), which lints and typechecks clean without it. This zone
  //     closes that gap the same way packages/domain's own zone does.
  {
    files: [
      "apps/mobile/src/**/*.ts",
      "apps/mobile/src/**/*.tsx",
      "apps/mobile/app/**/*.ts",
      "apps/mobile/app/**/*.tsx",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@smart-kitchen/domain",
              message:
                "apps/mobile must not import @smart-kitchen/domain directly. Use @smart-kitchen/contracts types instead (M3-T1 invariant).",
            },
          ],
          patterns: [
            {
              group: ["@smart-kitchen/domain/*"],
              message:
                "apps/mobile must not import @smart-kitchen/domain directly. Use @smart-kitchen/contracts types instead (M3-T1 invariant).",
            },
          ],
        },
      ],
      "import-x/no-restricted-paths": [
        "error",
        {
          zones: [
            {
              target: ["./apps/mobile/src", "./apps/mobile/app"],
              from: ["./packages/domain/src"],
              message:
                "apps/mobile must not reach into packages/domain/src by relative path. Use @smart-kitchen/contracts types instead (M3-T1 invariant).",
            },
          ],
        },
      ],
    },
  },
  // --- apps/mobile Node-global containment (M3-T2 review F3, extended F19) ---
  // `apps/mobile/src/lint-rules/copy-scan.test.ts` needs `/// <reference
  // types="node" />` to typecheck its real fs/path calls, but a triple-slash
  // reference is not actually file-scoped for TypeScript's *ambient global*
  // declarations (`process`, `Buffer`, `NodeJS.*`, `__dirname`, …): once any
  // file in the program pulls @types/node in, those globals type-check from
  // every other file too, which defeats the M3-T1 "Node's ambient globals
  // never leak into React Native app code" invariant at the type level (the
  // review proved `process.env.HOME`, `Buffer.from` and `NodeJS.Timeout`
  // type-check clean in `src/onboarding/validation.ts`). tsconfig's `"types":
  // []` cannot fix this — it only controls automatic inclusion, not what a
  // reference directive pulls in — so containment moves here instead:
  // referencing these five names as *globals* (not as locally declared
  // variables — a file with its own `declare const process = …` shadows the
  // global and is unaffected, e.g. `domain-boundary.test.ts`) is a lint error
  // everywhere in this app except `src/lint-rules/**`, where real Node access
  // is the point.
  //
  // Review F19: `no-restricted-globals` only catches the bare identifier
  // (`process`), not a member access through `globalThis` (`globalThis.
  // process`), which reaches the exact same ambient global by a different
  // path. Closed with `no-restricted-properties` targeting `globalThis.<name>`
  // for the same five names, rather than adding `"globalThis"` itself to
  // `no-restricted-globals`: `apps/mobile/src/api/client.test.ts` legitimately
  // mocks `globalThis.fetch` (a web standard, not a Node global), and
  // restricting the bare `globalThis` identifier would have flagged that too.
  // Targeting the five specific properties closes the bypass without that
  // collateral restriction. (`NodeJS.*` *types*, e.g. `NodeJS.Timeout` used as
  // a type annotation, remain visible everywhere by design — only runtime
  // global *values* are restricted here; a type has no runtime access to
  // anything.)
  //
  // M3-T3 adds one more exempted file: `src/config/env.ts` is the single
  // place `EXPO_PUBLIC_API_URL` is read (BACKLOG.md M3-T3 Objective (d)),
  // which needs the real `process` global the same way `src/lint-rules/**`
  // needs real Node access. Nothing else in this block changed.
  {
    files: [
      "apps/mobile/app/**/*.ts",
      "apps/mobile/app/**/*.tsx",
      "apps/mobile/src/**/*.ts",
      "apps/mobile/src/**/*.tsx",
    ],
    ignores: ["apps/mobile/src/lint-rules/**", "apps/mobile/src/config/env.ts"],
    rules: {
      "no-restricted-globals": [
        "error",
        {
          name: "process",
          message:
            "Node global; apps/mobile keeps Node's ambient globals out of app code (M3-T1 invariant). See src/lint-rules/ for the one exception.",
        },
        {
          name: "Buffer",
          message:
            "Node global; apps/mobile keeps Node's ambient globals out of app code (M3-T1 invariant). See src/lint-rules/ for the one exception.",
        },
        {
          name: "__dirname",
          message:
            "Node global; apps/mobile keeps Node's ambient globals out of app code (M3-T1 invariant). See src/lint-rules/ for the one exception.",
        },
        {
          name: "__filename",
          message:
            "Node global; apps/mobile keeps Node's ambient globals out of app code (M3-T1 invariant). See src/lint-rules/ for the one exception.",
        },
        {
          name: "global",
          message:
            "Node global; apps/mobile keeps Node's ambient globals out of app code (M3-T1 invariant). See src/lint-rules/ for the one exception.",
        },
      ],
      "no-restricted-properties": [
        "error",
        ...["process", "Buffer", "__dirname", "__filename", "global"].map((property) => ({
          object: "globalThis",
          property,
          message:
            "Node global reached through globalThis; apps/mobile keeps Node's ambient globals out of app code (M3-T1 invariant). See src/lint-rules/ for the one exception.",
        })),
      ],
    },
  },
  eslintConfigPrettier,
);
